openapi: 3.0.1
info:
  title: LiveAgent Async Event API
  description: 'This API is for async event communication'
  termsOfService: http://swagger.io/terms/
  contact:
    email: mcivan@qualityunit.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: https://petstore.swagger.io/v2
- url: http://petstore.swagger.io/v2
tags:
- name: events
  description: Calls about Domain events
  externalDocs:
    description: Find out more
    url: http://swagger.io
paths:
  /consumers:
    get:
      tags:
      - events
      summary: Get event consumer definitions 
      description: Consumer is defined by unique ID and list of event IDs it consumes
      operationId: getEventConsumers
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Consumer'
  /topics:
    get:
      tags:
      - events
      summary: Get event-topics mapping
      description: Topic is defined by unique ID and list of event IDs it contains
      operationId: getEventTopics
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Topic'    
components:
  schemas:
    Consumer:
      type: object
      properties:
        id:
          type: string
        events:
          type: array
          items:
            $ref: '#/components/schemas/Event'
    Event:
      type: object
      properties:
        id:
          type: string
    Topic:
      type: object
      properties:
        id:
          type: string
        events:
          type: array
          items:
            $ref: '#/components/schemas/Event'